/**:
  ros__parameters:
    obstacles:
      x: [-0.4, 0.7, 0.5, -0.3, 0.0]
      y: [-0.7, -0.8, 0.8, 0.5, -0.3]
      r: 0.038
    x0: -0.6
    y0: 0.3
    theta0: 1.28
    basic_sensor_variance: 0.001